project:
  type: book

book:
  title: "Computational Solid State Physics"
  author: "Jarvist Moore Frost"
  date: "2022-09-01"
  conver-image: "cover.svg"
  chapters:
    - index.qmd
    - intro.qmd
    - structure.qmd
    - dynamics.qmd
    - electronstructure.qmd
    - electrondynamics.qmd
    - zbibliography.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



